const novels = Object.freeze([
  { rank: 1, title: "Ulysses", author: "James Joyce", year: 1922 },
  { rank: 2, title: "The Great Gatsby", author: "F. Scott Fitzgerald", year: 1925 },
  { rank: 3, title: "A Portrait of the Artist as a Young Man", author: "James Joyce", year: 1916 },
  { rank: 4, title: "Lolita", author: "Vladimir Nabokov", year: 1955 },
  { rank: 5, title: "Brave New World", author: "Aldous Huxley", year: 1932 },
  { rank: 6, title: "The Sound and the Fury", author: "William Faulkner", year: 1929 },
  { rank: 7, title: "Catch-22", author: "Joseph Heller", year: 1961 },
  { rank: 8, title: "Darkness at Noon", author: "Arthur Koestler", year: 1940 },
  { rank: 9, title: "Sons and Lovers", author: "D. H. Lawrence", year: 1913 },
  { rank: 10, title: "The Grapes of Wrath", author: "John Steinbeck", year: 1939 },

  { rank: 11, title: "Under the Volcano", author: "Malcolm Lowry", year: 1947 },
  { rank: 12, title: "The Way of All Flesh", author: "Samuel Butler", year: 1903 },
  { rank: 13, title: "1984", author: "George Orwell", year: 1949 },
  { rank: 14, title: "I, Claudius", author: "Robert Graves", year: 1934 },
  { rank: 15, title: "To the Lighthouse", author: "Virginia Woolf", year: 1927 },
  { rank: 16, title: "An American Tragedy", author: "Theodore Dreiser", year: 1925 },
  { rank: 17, title: "The Heart Is a Lonely Hunter", author: "Carson McCullers", year: 1940 },
  { rank: 18, title: "Slaughterhouse-Five", author: "Kurt Vonnegut", year: 1969 },
  { rank: 19, title: "Invisible Man", author: "Ralph Ellison", year: 1952 },
  { rank: 20, title: "Native Son", author: "Richard Wright", year: 1940 },

  { rank: 21, title: "Henderson the Rain King", author: "Saul Bellow", year: 1959 },
  { rank: 22, title: "Appointment in Samarra", author: "John O’Hara", year: 1934 },
  { rank: 23, title: "U.S.A. (trilogy)", author: "John Dos Passos", year: 1938 },
  { rank: 24, title: "Winesburg, Ohio", author: "Sherwood Anderson", year: 1919 },
  { rank: 25, title: "A Passage to India", author: "E. M. Forster", year: 1924 },
  { rank: 26, title: "The Wings of the Dove", author: "Henry James", year: 1902 },
  { rank: 27, title: "The Ambassadors", author: "Henry James", year: 1903 },
  { rank: 28, title: "Tender Is the Night", author: "F. Scott Fitzgerald", year: 1934 },
  { rank: 29, title: "The Studs Lonigan Trilogy", author: "James T. Farrell", year: 1932 },
  { rank: 30, title: "The Good Soldier", author: "Ford Madox Ford", year: 1915 },

  { rank: 31, title: "Animal Farm", author: "George Orwell", year: 1945 },
  { rank: 32, title: "The Golden Bowl", author: "Henry James", year: 1904 },
  { rank: 33, title: "Sister Carrie", author: "Theodore Dreiser", year: 1900 },
  { rank: 34, title: "A Handful of Dust", author: "Evelyn Waugh", year: 1934 },
  { rank: 35, title: "As I Lay Dying", author: "William Faulkner", year: 1930 },
  { rank: 36, title: "All the King’s Men", author: "Robert Penn Warren", year: 1946 },
  { rank: 37, title: "The Bridge of San Luis Rey", author: "Thornton Wilder", year: 1927 },
  { rank: 38, title: "Howards End", author: "E.M. Forster", year: 1910 },
  { rank: 39, title: "Go Tell It on the Mountain", author: "James Baldwin", year: 1953 },
  { rank: 40, title: "The Heart of the Matter", author: "Graham Greene", year: 1948 },

  { rank: 41, title: "Lord of the Flies", author: "William Golding", year: 1954 },
  { rank: 42, title: "Deliverance", author: "James Dickey", year: 1970 },
  { rank: 43, title: "A Dance to the Music of Time (series)", author: "Anthony Powell", year: 1951 },
  { rank: 44, title: "Point Counter Point", author: "Aldous Huxley", year: 1928 },
  { rank: 45, title: "The Sun Also Rises", author: "Ernest Hemingway", year: 1926 },
  { rank: 46, title: "The Secret Agent", author: "Joseph Conrad", year: 1907 },
  { rank: 47, title: "Nostromo", author: "Joseph Conrad", year: 1904 },
  { rank: 48, title: "The Rainbow", author: "D.H. Lawrence", year: 1915 },
  { rank: 49, title: "Women in Love", author: "D.H. Lawrence", year: 1920 },
  { rank: 50, title: "Tropic of Cancer", author: "Henry Miller", year: 1934 },

  { rank: 51, title: "The Naked and the Dead", author: "Norman Mailer", year: 1948 },
  { rank: 52, title: "Portnoy’s Complaint", author: "Philip Roth", year: 1969 },
  { rank: 53, title: "Pale Fire", author: "Vladimir Nabokov", year: 1962 },
  { rank: 54, title: "Light in August", author: "William Faulkner", year: 1932 },
  { rank: 55, title: "On the Road", author: "Jack Kerouac", year: 1957 },
  { rank: 56, title: "The Maltese Falcon", author: "Dashiell Hammett", year: 1930 },
  { rank: 57, title: "Parade’s End", author: "Ford Madox Ford", year: 1924 },
  { rank: 58, title: "The Age of Innocence", author: "Edith Wharton", year: 1920 },
  { rank: 59, title: "Zuleika Dobson", author: "Max Beerbohm", year: 1911 },
  { rank: 60, title: "The Moviegoer", author: "Walker Percy", year: 1961 },

  { rank: 61, title: "Death Comes for the Archbishop", author: "Willa Cather", year: 1927 },
  { rank: 62, title: "From Here to Eternity", author: "James Jones", year: 1951 },
  { rank: 63, title: "The Wapshot Chronicle", author: "John Cheever", year: 1957 },
  { rank: 64, title: "The Catcher in the Rye", author: "J.D. Salinger", year: 1951 },
  { rank: 65, title: "A Clockwork Orange", author: "Anthony Burgess", year: 1962 },
  { rank: 66, title: "Of Human Bondage", author: "W. Somerset Maugham", year: 1915 },
  { rank: 67, title: "Heart of Darkness", author: "Joseph Conrad", year: 1902 },
  { rank: 68, title: "Main Street", author: "Sinclair Lewis", year: 1920 },
  { rank: 69, title: "The House of Mirth", author: "Edith Wharton", year: 1905 },
  { rank: 70, title: "The Alexandria Quartet", author: "Lawrence Durrell", year: 1957 },

  { rank: 71, title: "A High Wind in Jamaica", author: "Richard Hughes", year: 1929 },
  { rank: 72, title: "A House for Mr Biswas", author: "V.S. Naipaul", year: 1961 },
  { rank: 73, title: "The Day of the Locust", author: "Nathanael West", year: 1939 },
  { rank: 74, title: "A Farewell to Arms", author: "Ernest Hemingway", year: 1929 },
  { rank: 75, title: "Scoop", author: "Evelyn Waugh", year: 1938 },
  { rank: 76, title: "The Prime of Miss Jean Brodie", author: "Muriel Spark", year: 1961 },
  { rank: 77, title: "Finnegans Wake", author: "James Joyce", year: 1939 },
  { rank: 78, title: "Kim", author: "Rudyard Kipling", year: 1901 },
  { rank: 79, title: "A Room with a View", author: "E.M. Forster", year: 1908 },
  { rank: 80, title: "Brideshead Revisited", author: "Evelyn Waugh", year: 1945 },

  { rank: 81, title: "The Adventures of Augie March", author: "Saul Bellow", year: 1953 },
  { rank: 82, title: "Angle of Repose", author: "Wallace Stegner", year: 1971 },
  { rank: 83, title: "A Bend in the River", author: "V.S. Naipaul", year: 1979 },
  { rank: 84, title: "The Death of the Heart", author: "Elizabeth Bowen", year: 1938 },
  { rank: 85, title: "Lord Jim", author: "Joseph Conrad", year: 1900 },
  { rank: 86, title: "Ragtime", author: "E.L. Doctorow", year: 1975 },
  { rank: 87, title: "The Old Wives’ Tale", author: "Arnold Bennett", year: 1908 },
  { rank: 88, title: "The Call of the Wild", author: "Jack London", year: 1903 },
  { rank: 89, title: "Loving", author: "Henry Green", year: 1945 },
  { rank: 90, title: "Midnight’s Children", author: "Salman Rushdie", year: 1981 },

  { rank: 91, title: "Tobacco Road", author: "Erskine Caldwell", year: 1932 },
  { rank: 92, title: "Ironweed", author: "William Kennedy", year: 1984 },
  { rank: 93, title: "The Magus", author: "John Fowles", year: 1966 },
  { rank: 94, title: "Wide Sargasso Sea", author: "Jean Rhys", year: 1966 },
  { rank: 95, title: "Under the Net", author: "Iris Murdoch", year: 1954 },
  { rank: 96, title: "Sophie’s Choice", author: "William Styron", year: 1979 },
  { rank: 97, title: "The Sheltering Sky", author: "Paul Bowles", year: 1949 },
  { rank: 98, title: "The Postman Always Rings Twice", author: "James M. Cain", year: 1934 },
  { rank: 99, title: "The Ginger Man", author: "J.P. Donleavy", year: 1955 },
  { rank: 100, title: "The Magnificent Ambersons", author: "Booth Tarkington", year: 1918 }
]);

module.exports = novels;